<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $equipment = [
            [
                'name'             => 'Treadmill',
                'code'             => 'EQ-001',
                'description'      => 'Treadmill elektrik profesional dengan layar LCD, monitor detak jantung, dan berbagai program latihan.',
                'category'         => 'Cardio',
                'brand'            => 'Life Fitness',
                'quantity'         => 8,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-01-15',
                'last_maintenance' => '2026-01-10',
                'next_maintenance' => '2026-04-10',
            ],
            [
                'name'             => 'Elliptical Trainer',
                'code'             => 'EQ-002',
                'description'      => 'Mesin eliptikal untuk latihan kardio rendah dampak pada persendian.',
                'category'         => 'Cardio',
                'brand'            => 'Technogym',
                'quantity'         => 5,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-01-15',
                'last_maintenance' => '2026-01-10',
                'next_maintenance' => '2026-04-10',
            ],
            [
                'name'             => 'Stationary Bike',
                'code'             => 'EQ-003',
                'description'      => 'Sepeda statis untuk kelas spinning dan latihan kardio individu.',
                'category'         => 'Cardio',
                'brand'            => 'Schwinn',
                'quantity'         => 18,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-03-01',
                'last_maintenance' => '2026-02-01',
                'next_maintenance' => '2026-05-01',
            ],
            [
                'name'             => 'Rowing Machine',
                'code'             => 'EQ-004',
                'description'      => 'Mesin dayung Concept2 untuk latihan full body kardio.',
                'category'         => 'Cardio',
                'brand'            => 'Concept2',
                'quantity'         => 4,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-06-01',
                'last_maintenance' => '2026-01-15',
                'next_maintenance' => '2026-04-15',
            ],
            [
                'name'             => 'Dumbbell Set (2-40 kg)',
                'code'             => 'EQ-005',
                'description'      => 'Set dumbbell lengkap dari 2kg hingga 40kg dengan rak penyimpanan.',
                'category'         => 'Strength',
                'brand'            => 'Rogue Fitness',
                'quantity'         => 2,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-01-15',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Barbell Olympic Set',
                'code'             => 'EQ-006',
                'description'      => 'Barbell olimpik 20kg dengan set plate besi dari 1.25kg - 25kg.',
                'category'         => 'Strength',
                'brand'            => 'Eleiko',
                'quantity'         => 6,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-01-15',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Smith Machine',
                'code'             => 'EQ-007',
                'description'      => 'Smith machine dengan sistem counterbalance untuk latihan aman.',
                'category'         => 'Strength',
                'brand'            => 'Hammer Strength',
                'quantity'         => 2,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-02-01',
                'last_maintenance' => '2025-12-15',
                'next_maintenance' => '2026-03-15',
            ],
            [
                'name'             => 'Leg Press Machine',
                'code'             => 'EQ-008',
                'description'      => 'Mesin leg press 45 derajat untuk latihan kaki intensif.',
                'category'         => 'Strength',
                'brand'            => 'Cybex',
                'quantity'         => 2,
                'condition'        => 'Rusak Ringan',
                'purchase_date'    => '2024-02-01',
                'last_maintenance' => '2025-11-01',
                'next_maintenance' => '2026-02-25',
                'notes'            => 'Kabel pada unit 2 perlu diganti',
            ],
            [
                'name'             => 'Cable Crossover Machine',
                'code'             => 'EQ-009',
                'description'      => 'Mesin cable crossover dual pulley untuk berbagai latihan isolasi.',
                'category'         => 'Strength',
                'brand'            => 'Life Fitness',
                'quantity'         => 2,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-03-01',
                'last_maintenance' => '2026-01-20',
                'next_maintenance' => '2026-04-20',
            ],
            [
                'name'             => 'Lat Pulldown Machine',
                'code'             => 'EQ-010',
                'description'      => 'Mesin lat pulldown untuk latihan punggung dan bisep.',
                'category'         => 'Strength',
                'brand'            => 'Technogym',
                'quantity'         => 2,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-03-01',
                'last_maintenance' => '2026-01-20',
                'next_maintenance' => '2026-04-20',
            ],
            [
                'name'             => 'Bench Press (Flat/Incline/Decline)',
                'code'             => 'EQ-011',
                'description'      => 'Bench adjustable untuk latihan chest press dengan berbagai sudut.',
                'category'         => 'Strength',
                'brand'            => 'Rogue Fitness',
                'quantity'         => 4,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-01-15',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Kettlebell Set (4-32 kg)',
                'code'             => 'EQ-012',
                'description'      => 'Set kettlebell untuk latihan functional dan CrossFit.',
                'category'         => 'Functional',
                'brand'            => 'Rogue Fitness',
                'quantity'         => 3,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-06-01',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Battle Rope',
                'code'             => 'EQ-013',
                'description'      => 'Battle rope 15 meter untuk latihan kondisioning dan kekuatan grip.',
                'category'         => 'Functional',
                'brand'            => 'Generic',
                'quantity'         => 3,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-06-01',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Yoga Mat',
                'code'             => 'EQ-014',
                'description'      => 'Matras yoga premium anti-slip ketebalan 6mm.',
                'category'         => 'Flexibility',
                'brand'            => 'Manduka',
                'quantity'         => 30,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-04-01',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
            [
                'name'             => 'Foam Roller Set',
                'code'             => 'EQ-015',
                'description'      => 'Set foam roller untuk stretching dan pemulihan otot.',
                'category'         => 'Flexibility',
                'brand'            => 'TriggerPoint',
                'quantity'         => 15,
                'condition'        => 'Baik',
                'purchase_date'    => '2024-04-01',
                'last_maintenance' => null,
                'next_maintenance' => null,
            ],
        ];

        foreach ($equipment as $item) {
            DB::table('equipment')->insert(array_merge([
                'image'            => null,
                'notes'            => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ], $item));
        }
    }
}
